### ISSUE TITLE
Any VectorDrawable plugins?

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [balsikandar/Android-Studio-Plugins#2]
What I wish to have for VectorDrawable:

1. Ability to view all of them together, instead of one after another (each tab shows a single one).
Maybe even a plugin for the OS itself, to show them as thumbnails inside the folder...
2. Ability to convert multiple SVG files into VectorDrawable files.

Any of those available? Anything similar?

**Comment by balsikandar** [comment]
I'm looking for vector drawables but haven't found anything as per your requirement will update you if i get any such plugin. Thanks for raising issue.
These are few i found related to vector drawables check if any of these meets your need.
1- https://github.com/misakuo/svgtoandroid
2- https://github.com/winterDroid/android-drawable-importer-intellij-plugin
3- https://github.com/ligi/VectorDrawableImport

**Comment by AndroidDeveloperLB** [comment]
Nice. I think the svgtoandroid seems promising.
Still wish for view-all VectorDrawables (or all drawables in general). This can help finding images by content and not just by name.

**Comment by JxSx** [comment]
Cool!

**Comment by balsikandar** [comment]
If svgtoandroid  is good to go i'm closing this issue.

**Comment by AndroidDeveloperLB** [comment]
@balsikandar  Have you posted about it though?

**Comment by ignaciotcrespo** [comment]
This plugin show thumbnails for all the vector drawables in the project https://plugins.jetbrains.com/plugin/10741-vector-drawable-thumbnails

**Comment by AndroidDeveloperLB** [comment]
@ignaciotcrespo 
1. How can I trigger it?
2. Is it yours? If so, can you please also let the OS itself show the preview in the file-manager window ?

**Comment by ignaciotcrespo** [comment]
It is mine indeed, to trigger it just choose the tool in the bootom left icon where all the android studio tools are

![image](https://user-images.githubusercontent.com/6496116/40285505-3c652b10-5c73-11e8-9897-3d5c447f2c7f.png)

I dont understand whatyou mean with the `let the OS itself show the preview`

**Comment by AndroidDeveloperLB** [comment]
Where is that?
I thought I could see it here:

![image](https://user-images.githubusercontent.com/5357526/40292527-808f9de6-5cd4-11e8-92fe-8fa970d0e811.png)

**Comment by AndroidDeveloperLB** [comment]
Why this thread is closed?

**Comment by balsikandar** [comment]
my mistake i thought it worked from the picture above,
BTW seems like you installed the plugin but all vectors were not shown right?

**Comment by AndroidDeveloperLB** [comment]
Yes, I don't get how to show them.
I've been told about another plugin, but I also don't get how to show them:
https://plugins.jetbrains.com/plugin/10741-vector-drawable-thumbnails

**Comment by balsikandar** [comment]
it's the same link which ignaciotcrespo shared and if you installed it then from the pic he shared you can hover over desktop icon in bottom left of android studio and it should display "vector thumbnails" option with other tools.

**Comment by AndroidDeveloperLB** [comment]
@balsikandar Oh it's the same? Sorry it was a long time ago.
But still, how do I show them? Where is this "vector thumbnails" option?
How can I show this context menu?

**Comment by AndroidDeveloperLB** [comment]
Odd. On newest Android Studio, I don't see this menu, but I just see a tab on the right, so now it works there:

![image](https://user-images.githubusercontent.com/5357526/41309905-9fe3e970-6e88-11e8-8322-e5b3aa4694f3.png)

**Comment by balsikandar** [comment]
If it's working fine then we can close this issue

**Comment by AndroidDeveloperLB** [comment]
Yes ok.
But please publish it in the list of plugins.
And I wonder why someone said I should look at tools menu, if it's just in a tab...

**Comment by AndroidDeveloperLB** [comment]
Also, it could still be nice to see the VectorDrawables plugin work outside of Android Studio, on the file manager of the OS.

**Comment by balsikandar** [comment]
yeah i have added it in list of plugins. Thanks
