### ISSUE TITLE
Detect experimental and beta code

### ISSUE THREAD

**Issue by fooock** [balsikandar/Android-Studio-Plugins#5]
Hi! I created a new plugin for IntelliJ/Android Studio to detect code that is annotated with `@Experimental` or `@Beta` annotations and show an icon on the gutter. Can you add it to the list? Check out it [here](https://github.com/fooock/detect-experimental-and-beta-code). The name of the plugin is `Icons for Java annotations`

Cheers!

**Comment by balsikandar** [comment]
Hi i'll try this plugin and if it's good i'll add it in current project.

**Comment by vaibhavchugh09** [comment]
Ok sir...

Firstly i want to do some hand over MVP then i will try further stuff but
surely i will look over this plugin.
