### ISSUE TITLE
欢迎博主参考我总结的插件

### ISSUE THREAD

**Issue by AweiLoveAndroid** [balsikandar/Android-Studio-Plugins#6]
这是我总结的Android Studio插件，希望博主采纳
https://github.com/AweiLoveAndroid/The-pit-of-the-Android-Studio/blob/master/Android%20Studio%E5%A5%BD%E7%94%A8%E7%9A%84%E6%8F%92%E4%BB%B6(new).txt

**Comment by balsikandar** [comment]
It doesn't looks like related to Android Plugins so i'll close it
